### ISSUE TITLE
torch.nn.DataParallel error

### ISSUE THREAD

**Issue by anonymoussss** [szq0214/MEAL-V2#24]
I want to train MEAL-V2 on a machine with 4 gpus, the train script as follow :
python train.py --gpus 0 1 2 3 --save MEAL_V2_resnet50_224 ...

but get a error: 
```
... 
RuntimeError: Caught RuntimeError in replica 0 on device 0.
...
RuntimeError: Caught RuntimeError in replica 1 on device 1.
Original Traceback (most recent call last):
    File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
        output = module(*input, **kwargs)
    File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
        result = self.forward(*input, **kwargs)
    File "/mnt/codes/MEAL2-drink/models/discriminator.py", line 17, in forward
        out = F.relu(self.conv1(x))
    File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
         result = self.forward(*input, **kwargs)
    File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 399, in forward
         return self._conv_forward(input, self.weight, self.bias)
    File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 396, in _conv_forward
         self.padding, self.dilation, self.groups)
RuntimeError: Expected tensor for argument #1 'input' to have the same device as tensor for argument #2 'weight'; but device 1 does not equal 0 (while checking arguments for cudnn_convolution)
```

**Comment by szq0214** [comment]
Hi @anonymoussss, can you try:
CUDA_VISIBLE_DEVICES=0,1,2,3 python train.py --save MEAL_V2_resnet50_224 ...

**Comment by anonymoussss** [comment]
> Hi @anonymoussss, can you try: CUDA_VISIBLE_DEVICES=0,1,2,3 python train.py --save MEAL_V2_resnet50_224 ...

thanks, it works. :)
